import crypto from 'node:crypto';
import {supabaseConfigured,supabaseRequest} from './supabase';
export type StudentLevel='nguli'|'mandor'|'supervisor';
export interface StoredStudent{id:string;name:string;email:string;level:StudentLevel;active:boolean;password_hash:string;used_access_codes:string[]}
function hashPassword(password:string){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(password,salt,64).toString('hex');return `${salt}:${hash}`}
function verifyPassword(password:string,stored:string){const [salt,storedHash]=String(stored||'').split(':');if(!salt||!storedHash)return false;const derived=crypto.scryptSync(password,salt,64).toString('hex');const a=Buffer.from(derived,'hex'),b=Buffer.from(storedHash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
const memoryStudents=new Map<string,StoredStudent>();
for(const student of [{id:'usr-demo-1',name:'Pejuang SNBT 2026',email:'siswa@malasbelajar.id',level:'nguli' as StudentLevel},{id:'usr-mandor-1',name:'Siti Rahma',email:'siti@malasbelajar.id',level:'mandor' as StudentLevel},{id:'usr-spv-1',name:'Budi Santoso',email:'budi@malasbelajar.id',level:'supervisor' as StudentLevel}])memoryStudents.set(student.email,{...student,active:true,password_hash:hashPassword('demo123'),used_access_codes:[]});
function rowToStudent(r:any):StoredStudent{return{id:String(r.id),name:String(r.name||''),email:String(r.email||'').toLowerCase(),level:r.level as StudentLevel,active:r.active!==false,password_hash:String(r.password_hash||''),used_access_codes:Array.isArray(r.used_access_codes)?r.used_access_codes.map(String):[]}}
export function publicStudent(s:StoredStudent){return{id:s.id,name:s.name,email:s.email,level:s.level,active:s.active}}
export function passwordMatches(s:StoredStudent,password:string){return verifyPassword(password,s.password_hash)}
export async function listStudents(){if(!supabaseConfigured())return Array.from(memoryStudents.values());try{const rows=await supabaseRequest<any[]>('students?select=*&order=created_at.asc');const students=rows.map(rowToStudent);for(const s of students)memoryStudents.set(s.email,s);return students.length?students:Array.from(memoryStudents.values())}catch(e){console.error('STUDENT_LIST_ERROR',e);return Array.from(memoryStudents.values())}}
export async function findStudent(email:string){const clean=String(email||'').trim().toLowerCase();const local=memoryStudents.get(clean);if(local)return local;return (await listStudents()).find(s=>s.email===clean)||null}
export async function saveStudent(input:{name:string;email:string;level:StudentLevel;password:string;accessCode:string}){const student:StoredStudent={id:`student-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`,name:input.name,email:input.email.toLowerCase(),level:input.level,active:true,password_hash:hashPassword(input.password),used_access_codes:[input.accessCode.toUpperCase()]};memoryStudents.set(student.email,student);if(supabaseConfigured())await supabaseRequest('students',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(student)});return student}
export async function accessCodeAlreadyUsed(code:string){const normalized=String(code||'').trim().toUpperCase();if(!normalized)return false;const students=await listStudents();return students.some(s=>s.used_access_codes.includes(normalized))}
export async function markAccessCodeUsed(student:StoredStudent,code:string,newLevel?:StudentLevel){const normalized=String(code||'').trim().toUpperCase();const updated={...student,level:newLevel||student.level,used_access_codes:Array.from(new Set([...student.used_access_codes,normalized]))};memoryStudents.set(updated.email,updated);if(supabaseConfigured())await supabaseRequest(`students?id=eq.${encodeURIComponent(updated.id)}`,{method:'PATCH',body:JSON.stringify({level:updated.level,used_access_codes:updated.used_access_codes,updated_at:new Date().toISOString()})});return updated}
export async function setStudentActive(student:StoredStudent,active:boolean){const updated={...student,active};memoryStudents.set(updated.email,updated);if(supabaseConfigured())await supabaseRequest(`students?id=eq.${encodeURIComponent(updated.id)}`,{method:'PATCH',body:JSON.stringify({active})});return updated}
