import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Trash2 } from "lucide-react";
import { toast } from "sonner";

const SUBTESTS = [["pu","Penalaran Umum (PU)"],["ppu","Pengetahuan & Pemahaman Umum (PPU)"],["pbm","Pemahaman Bacaan & Menulis (PBM)"],["pk","Pengetahuan Kuantitatif (PK)"],["lit_indo","Literasi Bahasa Indonesia"],["lit_inggris","Literasi Bahasa Inggris"],["pm","Penalaran Matematika (PM)"]] as const;
type Level = "nguli" | "mandor" | "supervisor";
type Item = { id:string; title?:string; prompt?:string; chapter?:string; chapter_label?:string; kind?:string; subtest?:string; level?:string; difficulty?:string; url?:string };
const mentorCode=()=>{try{return sessionStorage.getItem("mls_mentor_code")||localStorage.getItem("mls_mentor_code")||"CECEKOKOMLS"}catch{return "CECEKOKOMLS"}};
async function jsonRequest<T>(url:string, options?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:"include",...options,headers:{"Content-Type":"application/json",...(options?.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.detail||body?.message||"Permintaan gagal.");return body as T;}

export default function MentorContentManager(){
 const [host,setHost]=useState<HTMLElement|null>(null); const [selected,setSelected]=useState("pu"); const [level,setLevel]=useState<Level>("nguli"); const [rodiItems,setRodiItems]=useState<Item[]>([]); const [wacaItems,setWacaItems]=useState<Item[]>([]); const [busy,setBusy]=useState("");
 const syncNative=(value:string)=>{for(const selector of ["[data-testid=\"admin-resource-subtest-select\"]","[data-testid=\"map-subtest-select\"]"]){const el=document.querySelector<HTMLSelectElement>(selector);if(el){el.value=value;el.dispatchEvent(new Event("change",{bubbles:true}));}}};
 const refresh=async()=>{try{const [q,w]=await Promise.all([jsonRequest<Item[]>("/api/mentor-content-v2?action=student-questions&level="+level),jsonRequest<Item[]>("/api/mentor-content-v2?action=wacawaci&level="+level)]);setRodiItems(Array.isArray(q)?q:[]);setWacaItems(Array.isArray(w)?w:(Array.isArray((w as any)?.items)?(w as any).items:[]));}catch(e:any){toast.error(e?.message||"Konten mentor gagal dimuat.");}};
 useEffect(()=>{const detect=()=>{const dashboard=document.querySelector<HTMLElement>("[data-testid=\"mentor-dashboard\"]");if(!dashboard){setHost(null);return;}const container=dashboard.querySelector<HTMLElement>(".mx-auto.max-w-7xl.px-5.py-8")||dashboard;let target=dashboard.querySelector<HTMLElement>("[data-testid=\"mentor-content-manager-host\"]");const plus=container.querySelector<HTMLElement>("[data-testid=\"mentor-dashboard-plus\"]");if(!target){target=document.createElement("div");target.setAttribute("data-testid","mentor-content-manager-host");}if(plus&&plus.parentElement===container){if(target.parentElement!==container||target.previousElementSibling!==plus)plus.insertAdjacentElement("afterend",target);}else if(target.parentElement!==container)container.prepend(target);setHost(target);};detect();const observer=new MutationObserver(detect);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();},[]);
 useEffect(()=>{if(host)void refresh();},[host,level]);
 if(!host)return null;
 const label=(id?:string)=>SUBTESTS.find(([key])=>key===id)?.[1]||id||"PU";
 const selectSubtest=(value:string)=>{setSelected(value);syncNative(value)};
 const remove=async(kind:"rodi"|"wacawaci",id:string)=>{if(!window.confirm(kind==="rodi"?"Hapus soal mentor ini?":"Hapus materi Wacawaci ini?"))return;try{setBusy(kind+"-"+id);const action=kind==="rodi"?"delete-question":"delete-wacawaci";await jsonRequest("/api/mentor-content-v2?action="+action+"&id="+encodeURIComponent(id)+"&mentor_code="+encodeURIComponent(mentorCode()),{method:"DELETE"});toast.success(kind==="rodi"?"Soal mentor dihapus.":"Materi Wacawaci dihapus.");await refresh();}catch(e:any){toast.error(e?.message||"Gagal menghapus konten.");}finally{setBusy("")}};
 return createPortal(<section className="mb-6 rounded-xl border-4 border-violet-950 bg-white p-4 shadow-[4px_4px_0_#2e1065]" data-testid="mentor-content-manager">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[10px] font-black uppercase tracking-widest text-violet-600">KONTEN MENTOR</p><h2 className="text-lg font-black text-violet-950">Pilih Loker Subtes + Kelola Upload</h2><p className="text-xs text-slate-500">Pilihan loker dipakai saat menambah soal RODI dan materi Wacawaci.</p></div><div className="flex gap-2"><select value={selected} onChange={e=>selectSubtest(e.target.value)} className="rounded-lg border-2 border-violet-950 bg-yellow-100 px-3 py-2 text-sm font-black" data-testid="mentor-subtest-select">{SUBTESTS.map(([id,text])=><option key={id} value={id}>{text}</option>)}</select><select value={level} onChange={e=>setLevel(e.target.value as Level)} className="rounded-lg border-2 border-violet-950 bg-white px-3 py-2 text-sm font-black"><option value="nguli">Nguli</option><option value="mandor">Mandor</option><option value="supervisor">Supervisor</option></select></div></div>
  <div className="mt-4 grid gap-4 lg:grid-cols-2">
   <div className="rounded-xl border-2 border-violet-200 bg-violet-50 p-3"><div className="flex items-center justify-between"><b className="text-violet-950">RODI TERUPLOAD</b><span className="font-mono text-xs">{rodiItems.length}</span></div><div className="mt-2 max-h-56 space-y-2 overflow-y-auto">{rodiItems.map(item=><div key={item.id} className="flex items-center justify-between gap-2 rounded-lg border-2 border-violet-200 bg-white p-2"><div className="min-w-0"><p className="truncate text-xs font-black text-violet-950">{item.prompt||item.title||"Soal mentor"}</p><p className="truncate text-[10px] text-slate-500">{label(item.chapter)} · {item.level||level} · {item.difficulty||"Mentor"}</p></div><button type="button" onClick={()=>void remove("rodi",item.id)} disabled={busy==="rodi-"+item.id} className="shrink-0 rounded-md border-2 border-violet-950 bg-pink-300 p-1.5 text-violet-950" aria-label="Hapus soal"><Trash2 className="h-4 w-4"/></button></div>)}{!rodiItems.length&&<p className="py-4 text-center text-xs text-slate-500">Belum ada soal RODI tambahan untuk level ini.</p>}</div></div>
   <div className="rounded-xl border-2 border-violet-200 bg-pink-50 p-3"><div className="flex items-center justify-between"><b className="text-violet-950">WACAWACI TERUPLOAD</b><span className="font-mono text-xs">{wacaItems.length}</span></div><div className="mt-2 max-h-56 space-y-2 overflow-y-auto">{wacaItems.map(item=><div key={item.id} className="flex items-center justify-between gap-2 rounded-lg border-2 border-pink-200 bg-white p-2"><div className="min-w-0"><p className="truncate text-xs font-black text-violet-950">{item.title||"Materi Wacawaci"}</p><p className="truncate text-[10px] text-slate-500">{label(item.subtest)} · {item.kind||"module"} · {item.level||level}</p></div>{String(item.id).startsWith("drive-")?<a href={item.url} target="_blank" rel="noreferrer" className="shrink-0 rounded-md border-2 border-violet-950 bg-yellow-300 px-2 py-1 text-[10px] font-black text-violet-950">BUKA</a>:<button type="button" onClick={()=>void remove("wacawaci",item.id)} disabled={busy==="wacawaci-"+item.id} className="shrink-0 rounded-md border-2 border-violet-950 bg-pink-300 p-1.5 text-violet-950" aria-label="Hapus materi"><Trash2 className="h-4 w-4"/></button>}</div>)}{!wacaItems.length&&<p className="py-4 text-center text-xs text-slate-500">Belum ada materi Wacawaci untuk level ini.</p>}</div></div>
  </div>
 </section>,host);
}