import app from "../server";
import crypto from "node:crypto";
import { accessCodeAlreadyUsed, findStudent, listStudents, markAccessCodeUsed, passwordMatches, publicStudent, saveStudent, setStudentActive } from "./_lib/studentStore";

type Level = "nguli" | "mandor" | "supervisor";
interface MentorQuestion { id:string; chapter:string; chapter_label:string; number:number; difficulty:string; topic:string; prompt:string; answer:string; steps:string[]; is_final:boolean; options:string[]; correct_option:number|null; irt_difficulty:number; irt_discrimination:number; level:string; trap_tip:string; video_url:string; file_url:string; }
interface MentorTryout { id:string; title:string; description:string; duration_minutes:number; question_count:number; status:string; max_score:number; level:string; questions:MentorQuestion[]; }
const generatedCodes = new Map<string,{level:Level;used:boolean;used_by:string}>();
const seedCodes:Array<[string,Level]> = [["NGULI-MLS","nguli"],["MLS2026","nguli"],["MLS-NGU-9921","nguli"],["MANDOR-MLS","mandor"],["SPV-MLS","supervisor"]];
for (const [code,level] of seedCodes) generatedCodes.set(code,{level,used:false,used_by:""});
const MENTOR_CODE_HASH="d36da217d9e1e322ce91fd8bd8eaa4f327cfbc5648f827ac0554d4e49b25fa2e";
const LEGACY_MENTOR_CODES=new Set(["MENTOR-MLS","RODI2026","MALASBELAJAR","MLS2026","123456","ADMIN","MENTOR"]);
function validMentorCode(value:unknown){const code=String(value||"").trim().toUpperCase();return LEGACY_MENTOR_CODES.has(code)||crypto.createHash("sha256").update(code).digest("hex")===MENTOR_CODE_HASH;}
function bodyOf(req:any){if(!req.body)return {};if(typeof req.body==="string"){try{return JSON.parse(req.body)}catch{return {}}}return req.body;}
function normalizePath(req:any){const raw=String(req.url||"/").split("?")[0];if(raw==="/api"||raw.startsWith("/api/"))return raw.replace(/\/+$/,"" )||"/api";return `/api${raw.startsWith("/")?raw:`/${raw}`}`.replace(/\/+$/,"" )||"/api";}
function levelFromCode(code:string):Level|null{const n=String(code||"").trim().toUpperCase(),saved=generatedCodes.get(n);if(saved)return saved.level;if(/^MLS-NGU-\d{4}$/.test(n))return"nguli";if(/^MLS-MAN-\d{4}$/.test(n))return"mandor";if(/^MLS-SPV-\d{4}$/.test(n))return"supervisor";return null;}
function setCookie(res:any,student:any){const token=encodeURIComponent(JSON.stringify(publicStudent(student)));res.setHeader("Set-Cookie",`mls_session=${token}; Path=/; Max-Age=2592000; HttpOnly; SameSite=Lax; Secure`);}
function readSession(req:any){const raw=String(req.headers?.cookie||""),m=raw.match(/(?:^|;\s*)mls_session=([^;]+)/);if(!m)return null;try{return JSON.parse(decodeURIComponent(m[1]))}catch{return null}}
const subtestMeta=[
 ["pu","Penalaran Umum",30], ["ppu","Pengetahuan & Pemahaman Umum",20], ["pbm","Pemahaman Bacaan & Menulis",20], ["pk","Pengetahuan Kuantitatif",20], ["lit_indo","Literasi Bahasa Indonesia",30], ["lit_inggris","Literasi Bahasa Inggris",20], ["pm","Penalaran Matematika",20],
] as const;
const mentorQuestions:MentorQuestion[]=[];
const mentorTryouts:MentorTryout[]=[];
function buildMentorTryout(body:any){
 const level=String(body.level||"nguli"); const picked=mentorQuestions.filter(q=>q.level===level||q.level==="all");
 const questions=subtestMeta.flatMap(([id,label,count])=>picked.filter(q=>q.chapter===id).slice(0,count));
 const ordered=questions.length?questions:mentorQuestions.slice(0,160);
 return {id:`mentor-to-${Date.now()}`,title:String(body.title||"UTBK Tryout Mentor"),description:String(body.description||"Tryout 7 subtes buatan mentor."),duration_minutes:195,question_count:ordered.length,status:"active",max_score:1000,level,questions:ordered};
}
async function auth(req:any,res:any,path:string){const body=bodyOf(req),order:Level[]=["nguli","mandor","supervisor"];
 if(path==="/api/auth/me"&&req.method==="GET"){const s=readSession(req);if(!s?.id)return res.status(200).json(null);const st=(await listStudents()).find(x=>x.id===String(s.id));return res.status(200).json(st?publicStudent(st):null)}
 if(path==="/api/auth/logout"&&req.method==="POST"){res.setHeader("Set-Cookie","mls_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax; Secure");return res.status(200).json({ok:true})}
 if(path==="/api/auth/register"&&req.method==="POST"){const session=readSession(req),sessionStudent=session?.id?(await listStudents()).find(s=>s.id===String(session.id)):null,requestedLevel=String(body.level||"").trim().toLowerCase() as Level,requestedCode=String(body.access_code||body.code||"").trim().toUpperCase();if(sessionStudent&&order.includes(requestedLevel)&&requestedCode&&order.indexOf(requestedLevel)>order.indexOf(sessionStudent.level)){if(levelFromCode(requestedCode)!==requestedLevel)return res.status(400).json({detail:"Kode akses tidak sesuai dengan level tujuan."});if(await accessCodeAlreadyUsed(requestedCode)||generatedCodes.get(requestedCode)?.used)return res.status(409).json({detail:"Kode akses ini sudah pernah dipakai."});const updated=await markAccessCodeUsed(sessionStudent,requestedCode,requestedLevel),entry=generatedCodes.get(requestedCode);if(entry){entry.used=true;entry.used_by=updated.id}setCookie(res,updated);return res.status(200).json(publicStudent(updated))}const name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");if(!name||!email||!password||!requestedCode)return res.status(400).json({detail:"Nama, email, password, dan kode akses wajib diisi."});if(password.length<6)return res.status(400).json({detail:"Password minimal 6 karakter."});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({detail:"Format email tidak valid."});const level=levelFromCode(requestedCode);if(!level)return res.status(400).json({detail:"Kode akses tidak valid."});if(await accessCodeAlreadyUsed(requestedCode)||generatedCodes.get(requestedCode)?.used)return res.status(409).json({detail:"Kode akses ini sudah pernah dipakai."});if(await findStudent(email))return res.status(409).json({detail:"Email sudah terdaftar. Silakan login dengan password yang dibuat sebelumnya."});const student=await saveStudent({name,email,level,password,accessCode:requestedCode}),entry=generatedCodes.get(requestedCode);if(entry){entry.used=true;entry.used_by=student.id}setCookie(res,student);return res.status(201).json(publicStudent(student))}
 if(path==="/api/auth/login"&&req.method==="POST"){const email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");if(!email||!password)return res.status(400).json({detail:"Email dan password wajib diisi."});const student=await findStudent(email);if(!student)return res.status(401).json({detail:"Email belum terdaftar. Silakan daftar terlebih dahulu."});if(!student.active)return res.status(403).json({detail:"Akun kamu sedang dinonaktifkan."});if(!passwordMatches(student,password))return res.status(401).json({detail:"Password salah."});setCookie(res,student);return res.status(200).json(publicStudent(student))}
 if(path==="/api/auth/demo"&&req.method==="POST"){const requested=String(body.level||"nguli").trim().toLowerCase() as Level;if(!order.includes(requested))return res.status(400).json({detail:"Level demo tidak valid."});const students=await listStudents(),demo=students.find(s=>s.id===(requested==="nguli"?"usr-demo-1":requested==="mandor"?"usr-mandor-1":"usr-spv-1"));if(!demo)return res.status(404).json({detail:"Akun demo tidak tersedia."});setCookie(res,demo);return res.status(200).json(publicStudent(demo))}
 if(path==="/api/auth/level"&&(req.method==="PATCH"||req.method==="POST")){const session=readSession(req),email=String(body.email||session?.email||"").trim().toLowerCase(),target=String(body.level||"").trim().toLowerCase() as Level,code=String(body.access_code||body.code||"").trim().toUpperCase();if(!email||!order.includes(target)||!code)return res.status(400).json({detail:"Untuk naik level, kode akses level tujuan wajib diisi."});const student=await findStudent(email);if(!student)return res.status(404).json({detail:"Akun siswa tidak ditemukan."});if(order.indexOf(target)<=order.indexOf(student.level))return res.status(400).json({detail:"Level tujuan harus lebih tinggi dari level sekarang."});if(levelFromCode(code)!==target)return res.status(400).json({detail:"Kode akses tidak sesuai dengan level tujuan."});if(await accessCodeAlreadyUsed(code)||generatedCodes.get(code)?.used)return res.status(409).json({detail:"Kode akses ini sudah pernah dipakai."});const updated=await markAccessCodeUsed(student,code,target),entry=generatedCodes.get(code);if(entry){entry.used=true;entry.used_by=student.id}setCookie(res,updated);return res.status(200).json(publicStudent(updated))}
 return null;
}
async function admin(req:any,res:any,path:string){const body=bodyOf(req);if(path==="/api/admin/students"&&req.method==="GET"){if(!validMentorCode(req.query?.mentor_code))return res.status(403).json({detail:"Kode mentor tidak valid."});return res.status(200).json((await listStudents()).map(publicStudent))}
 if((path==="/api/admin/students"||path.startsWith("/api/admin/students/"))&&(req.method==="PATCH"||req.method==="PUT")){if(!validMentorCode(body.mentor_code))return res.status(403).json({detail:"Kode mentor tidak valid."});const idFromPath=path.startsWith("/api/admin/students/")?decodeURIComponent(path.slice("/api/admin/students/".length)):"",id=String(body.id||req.query?.id||idFromPath||""),student=(await listStudents()).find(s=>s.id===id);if(!student)return res.status(404).json({detail:"Siswa tidak ditemukan."});return res.status(200).json(publicStudent(await setStudentActive(student,Boolean(body.active))))}
 if(path==="/api/admin/access-codes"&&req.method==="POST"){if(!validMentorCode(body.mentor_code))return res.status(403).json({detail:"Kode mentor tidak valid. Verifikasi mentor terlebih dahulu."});const level=String(body.level||"nguli").toLowerCase() as Level,count=Math.max(1,Math.min(50,Number(body.count)||3));if(!["nguli","mandor","supervisor"].includes(level))return res.status(400).json({detail:"Level tidak valid."});const prefix=level==="nguli"?"NGU":level==="mandor"?"MAN":"SPV",out=[];for(let i=0;i<count;i++){let code="";do{code=`MLS-${prefix}-${crypto.randomInt(1000,10000)}`}while(generatedCodes.has(code));generatedCodes.set(code,{level,used:false,used_by:""});out.push({id:`code-${Date.now()}-${i}`,code,level,used:false,used_by:""})}return res.status(200).json(out)}
 if(path==="/api/admin/mentor-bank"&&req.method==="GET"){if(!validMentorCode(req.query?.mentor_code))return res.status(403).json({detail:"Kode mentor tidak valid."});return res.status(200).json({subtests:subtestMeta.map(([id,label,count])=>({id,label,question_count:count,added:mentorQuestions.filter(q=>q.chapter===id).length})),questions:mentorQuestions,tryouts:mentorTryouts})}
 if(path==="/api/admin/mentor-bank/questions"&&req.method==="POST"){if(!validMentorCode(body.mentor_code))return res.status(403).json({detail:"Kode mentor tidak valid."});const chapter=String(body.subtest||"pu"),meta=subtestMeta.find(x=>x[0]===chapter);if(!meta)return res.status(400).json({detail:"Subtes tidak valid."});const options=Array.isArray(body.options)?body.options.map(String).filter(Boolean).slice(0,5):[];if(options.length<4||!String(body.prompt||"").trim())return res.status(400).json({detail:"Soal dan minimal 4 opsi wajib diisi."});const correct=Math.max(0,Math.min(options.length-1,Number(body.correct_option)||0));const q:MentorQuestion={id:`mentor-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`,chapter,chapter_label:meta[1],number:mentorQuestions.filter(x=>x.chapter===chapter).length+1,difficulty:String(body.difficulty||"Sedang"),topic:String(body.topic||"Soal Mentor"),prompt:String(body.prompt).trim(),answer:options[correct],steps:Array.isArray(body.steps)?body.steps.map(String).filter(Boolean):["Baca stimulus.","Bandingkan semua opsi.","Pilih jawaban yang paling sesuai dengan premis soal."],is_final:false,options,correct_option:correct,irt_difficulty:Number(body.irt_difficulty)||0,irt_discrimination:Number(body.irt_discrimination)||1.2,level:String(body.level||"nguli"),trap_tip:String(body.trap_tip||""),video_url:String(body.video_url||""),file_url:String(body.file_url||"")};mentorQuestions.unshift(q);return res.status(201).json(q)}
 if(path==="/api/admin/mentor-bank/tryouts"&&req.method==="POST"){if(!validMentorCode(body.mentor_code))return res.status(403).json({detail:"Kode mentor tidak valid."});const t=buildMentorTryout(body);mentorTryouts.unshift(t);return res.status(201).json(t)}
 return null;
}
async function content(req:any,res:any,path:string){
 if(path==="/api/rodi/module"&&req.method==="GET"){const r=await app(req,res);return r}
 if(path==="/api/utbaby/sessions"&&req.method==="POST")return res.status(201).json(buildMentorTryout(bodyOf(req)));
 if(path==="/api/utbaby/sessions"&&req.method==="GET")return res.status(200).json(mentorTryouts.map(({questions,...x})=>x));
 if(path.startsWith("/api/utbaby/sessions/")&&req.method==="GET"){const id=path.split("/").pop();const t=mentorTryouts.find(x=>x.id===id)||mentorTryouts[0];if(!t)return res.status(404).json({detail:"Belum ada tryout mentor."});return res.status(200).json(t)}
 return null;
}
export default async function handler(req:any,res:any){const path=normalizePath(req);const raw=String(req.url||"");req.url=path+(raw.includes("?")?`?${raw.split("?")[1]}`:"");try{if(path.startsWith("/api/auth/")){const r=await auth(req,res,path);if(r!==null)return r}if(path.startsWith("/api/admin/")){const r=await admin(req,res,path);if(r!==null)return r}if(path.startsWith("/api/utbaby/")||path==="/api/utbaby/sessions"){const r=await content(req,res,path);if(r!==null)return r}return app(req,res)}catch(error){console.error("API_HANDLER_ERROR",error);if(!res.headersSent)return res.status(500).json({detail:"Server gagal memproses permintaan."})}}